### ISSUE TITLE
The Python Version

### ISSUE THREAD

**Issue by PlentyMore** [More-A/prtest#1]
should I use py2 or py3?

**Comment by More-A** [comment]
you may use py3

**Comment by PlentyMore** [comment]
thanks for replying,I will install py3.

**Comment by More-A** [comment]
@PlentyMore No thanks,keep contributing.

**Comment by PlentyMore** [comment]
@More-A Notification test

**Comment by More-A** [comment]
@PlentyMore Reply

**Comment by More-A** [comment]
@PlentyMore Any notification received???

**Comment by PlentyMore** [comment]
Yes

**Comment by PlentyMore** [comment]
closed???why?

**Comment by PlentyMore** [comment]
#2
